# Nombre del microservicio
spring.application.name=msusuarios
spring.security.filter.dispatcher-types=async,error,request

# Puerto del microservicio
server.port=8081
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
app.jwt.secret=${APP_JWT_SECRET}
app.jwt.expiration-ms=${APP_JWT_EXPIRATION_MS:900000}

# Driver
spring.datasource.driver-class-name=org.postgresql.Driver
# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
# Charset
server.servlet.encoding.charset=UTF-8
server.servlet.encoding.enabled=true
server.servlet.encoding.force=true


spring.flyway.enabled=false
spring.flyway.baseline-on-migrate=false
logging.level.org.flywaydb=DEBUG
logging.level.org.flywaydb.core.internal.command=DEBUG
logging.level.org.flywaydb.core.internal.sqlscript=DEBUG

server.forward-headers-strategy=framework
logging.level.org.springframework.security=DEBUG

# --- Detalles de requests/responses ---
spring.mvc.log-request-details=true

# --- Errores HTTP (incluye mensaje/binding/stacktrace) ---
server.error.include-message=always
server.error.include-binding-errors=always
server.error.include-stacktrace=always

# --- Access log de Tomcat (útil para correlacionar) ---
server.tomcat.accesslog.enabled=true
server.tomcat.accesslog.directory=/app/logs
server.tomcat.accesslog.pattern=%h %l %u %t "%r" %s %b "%{Referer}i" "%{User-Agent}i" %D
server.tomcat.basedir=/app

# --- Archivos de log (además de stdout de Docker) ---
logging.file.name=/app/logs/msusuarios.log
logging.logback.rollingpolicy.max-history=7
logging.logback.rollingpolicy.max-file-size=50MB