spring.datasource.url=jdbc:postgresql://77.237.237.126:5433/usuariosdb?sslmode=require
spring.datasource.username=impulsofirme
spring.datasource.password=gydveh-1gykcE-cokqiv
spring.jpa.hibernate.ddl-auto=update