# Nombre del microservicio
spring.application.name=msusuarios
spring.security.filter.dispatcher-types=async,error,request

# Puerto del microservicio
server.port=8081
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
app.jwt.secret=${APP_JWT_SECRET}
app.jwt.expiration-ms=${APP_JWT_EXPIRATION_MS:900000}

# Driver
spring.datasource.driver-class-name=org.postgresql.Driver
# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
# Charset
server.servlet.encoding.charset=UTF-8
server.servlet.encoding.enabled=true
server.servlet.encoding.force=true


spring.flyway.enabled=false
spring.flyway.baseline-on-migrate=false
logging.level.org.flywaydb=DEBUG
logging.level.org.flywaydb.core.internal.command=DEBUG
logging.level.org.flywaydb.core.internal.sqlscript=DEBUG

server.forward-headers-strategy=framework