# === Configuración general de la aplicación ===
spring.application.name=msusuarios
server.port=8081
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
app.jwt.secret=${APP_JWT_SECRET}
app.jwt.expiration-ms=${APP_JWT_EXPIRATION_MS:900000}


# === JPA/Hibernate ===
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# === Errores HTTP: incluir mensaje y stacktrace (útil en dev) ===
server.error.include-message=always
server.error.include-stacktrace=always

# === Logging: limpio pero mostrando tus errores ===
logging.level.root=INFO
logging.level.org.springframework=INFO
logging.level.com.impulsofirme=DEBUG      # <-- tu paquete: verás tus excepciones y mensajes
logging.level.org.hibernate=INFO